apiVersion: v1
kind: Config 
clusters: 
    - name: authn
      cluster: 
        insecure-skip-tls-verify: true
        server: "https://192.168.0.254"

users:
  - name: kube-apiserver

current-context: authn
contexts: 
- context:
    cluster: authn
    user: kube-apiserver
  name: authn
